source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'json'

gem 'rack'
gem 'rack-protection'

gem 'sinatra'

group :development, :test do
  gem 'rspec'
  gem 'capybara'
end
